### PR TITLE
Implement Timed Achievement Modifications

### PR DESCRIPTION
**Pull request by wgpierce**
This feature is only implemented in the GUI for now. The GUI will hang
until all the achievements are done being modified currently.
All timed achievements modification options are implemented.

Subsequent commits will be added to address the GUI hang. I'll probably use another glib idle thread.
CLI support will also be implemented.

### CODE REVIEW

**Comment by PaulCombal** [comment]
Hmm how do you feel about making a release first? Do you think the current code in dev is production-ready?

**Comment by wgpierce** [comment]
I'm fine with making a release now. I just pushed an easy fix for Ubuntu 18.04 builds, so SamRewritten can build there.

**Comment by PaulCombal** [comment]
Alright, feel free to merge dev into master first, I think It's better to work further on the tied achievements after. Also, don't worry too much about 18.04. Now that 20.04 is out it should be the least of our concerns. Of course if it's a simple fix that's always good to take.

**Comment by wgpierce** [comment]
It is feature-complete now. It might be good to separate the timed modifications feature into its own object out of the MainPickerWindow, but I wanted to get it functional first.

**Pull request merged**
