### PR TITLE
new icon made by @rejedai

### LINKED ISSUE #14: Icon concept
I drew an icon, how about using it.

icon

### PR DESCRIPTION
**Pull request by telans**
Closes #14 

- new icon
- a minor string change

### CODE REVIEW

**Comment by telans** [comment]
The changes of `open-menu` and `popovermenu` were generated by Glade, presumably due to editing with a more recent version. Updates to GTK and all. I couldn't tell a visual or functional difference

**Comment by telans** [comment]
rebased onto master

**Comment by wgpierce** [comment]
Merged, thanks telans.

**Comment by wgpierce** [comment]
Sorry, now merged, thanks @telans !

**Comment by telans** [comment]
Great, added the changes to the PKGBUILD too

**Pull request merged**
