### PR TITLE
[fix] Not building after update

### PR DESCRIPTION
**Pull request by parov0z**
I just got the following error:
`error: 'uint64_t' does not name a type`
After cstdint is included, the error gone

### CODE REVIEW

**Review by RadiantOblivion — APPROVED** [review]
Can confirm this was an issue for building on Arch 6.3.1. Replicated fix by adding included changes to the files.

**Comment by PaulCombal** [comment]
Can you check again now? Sorry for the delay

**Comment by RadiantOblivion** [comment]
Screenshot from 2023-05-14 02-19-44

Yep still failing to build without cstdint. Must be a recent library change.

**Comment by PaulCombal** [comment]
I meant is it good to merge like this?

**Comment by RadiantOblivion** [comment]
Oh my bad let me check again one sec

Edit: Yep good to go. Commits fix issue on Arch 6.3.2-arch1-1.

**Review by RadiantOblivion — APPROVED** [review]

**Pull request merged**
