### PR TITLE
vscode / script changes

### PR DESCRIPTION
**Pull request by telans**

### CODE REVIEW

**Comment by PaulCombal** [comment]
Looks great! We'll first do a big release, then we will probably merge this.
One thing though, can you keep the executable name to lowercase `./bin/samrewritten`?
It would respect the POSIX conventions [(see guideline 2)](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html#tag_12_02)

In the future I'll look into making an AppImage, I believe the uppercase letters makes sense for this.

Thanks!

**Comment by telans** [comment]
Will do

**Comment by wgpierce** [comment]
LGTM.  telans, I was going to make a PKGBUILD sometime for arch distros. If you want to make it sometime before I get to it, that'd be cool too. Then we can put it on the AUR if we want to.

**Comment by telans** [comment]
@wgpierce 

There's already [an AUR package](https://aur.archlinux.org/packages/sam-rewritten-git/), but I don't like how the name `samrewritten` is hyphenated. It also installs files which are not needed.

I did modify that PKGBUILD a bit so only required files are installed. This also uses the beta-ipc branch.

```
pkgname="samrewritten-git"
_pkgname="SamRewritten"
pkgver=r58.b13cdcf
pkgrel=1
pkgdesc="A Steam Achievement Manager For Linux."
arch=("any")
url="https://github.com/PaulCombal/SamRewritten"
license=("GPL3")
depends=("steam" "yajl" "gtk3" "glibc")
makedepends=("git")
conflicts=("sam-rewritten-git")
source=("git+https://github.com/PaulCombal/SamRewritten.git#branch=beta-ipc")
md5sums=("SKIP")

pkgver() {
    cd ${_pkgname}
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
    cd ${_pkgname}
    ./make.sh
}

package() {  
    install -dm755 "${pkgdir}/usr/lib/"
    cp -r ${_pkgname} "${pkgdir}/usr/lib/"
    install -dm755 "${pkgdir}/usr/bin"
    ln -s "${pkgdir}/usr/lib/${_pkgname}/bin/launch.sh" "${pkgdir}/usr/bin/samrewritten"

    rm -rf ${pkgdir}/usr/lib/${_pkgname}/{.git*,.vscode,bin/test,src,steam/*.*}
}
```

**Comment by wgpierce** [comment]
Oh dang I didn't find that package before because of its hyphenation. Don't put out the beta-ipc branch yet until we merge to master -- we're almost there.

@telans your version still includes a bunch of unneeded files:

```bash
# short output from pacman -Qlp samrewritten-git-r58.b13cdcf-1-any.pkg.tar
# of files that are not needed:

samrewritten-git /usr/lib/SamRewritten/bin/.gitignore
samrewritten-git /usr/lib/SamRewritten/glade/.gitignore
samrewritten-git /usr/lib/SamRewritten/glade/mockup_achievement_list_row.glade
samrewritten-git /usr/lib/SamRewritten/make.sh
samrewritten-git /usr/lib/SamRewritten/steam/
samrewritten-git /usr/lib/SamRewritten/steam/lib/
samrewritten-git /usr/lib/SamRewritten/steam/lib/linux32/
samrewritten-git /usr/lib/SamRewritten/steam/lib/linux32/libsdkencryptedappticket.so
samrewritten-git /usr/lib/SamRewritten/steam/lib/linux64/
samrewritten-git /usr/lib/SamRewritten/steam/lib/linux64/libsdkencryptedappticket.so
```

You only really need samrewritten, libsteam_api.so, launch.sh, and main_window.glade, and probably README.md and LICENSE currently, so it'd probably be easier to just manually include all those.

**Comment by telans** [comment]
Would you happen to know what `libsdkencryptedappticket.so` is used for?

**Comment by wgpierce** [comment]
They're not used for anything; they're just artifacts of where Paul gets the steam_api library headers. I just tried compiling and running without them and nothing went wrong, so nothing uses them. They could probably be removed.

**Comment by nomis6432** [comment]
@telans I've added you as a maintainer in the AUR since you are a contributor to the project and know how PKGBUILDs work. Feel free to push the changes to remove certain unnecessary files to the AUR package.

Changing the AUR name could be done by creating a new package and requesting the old package to be merged with the new one.

**Comment by telans** [comment]
> You only really need samrewritten, libsteam_api.so, launch.sh, and main_window.glade, and probably README.md and LICENSE currently, so it'd probably be easier to just manually include all those.

I'd rather not whitelist files, for example with #16 if (when?) that gets merged, the image would need to be added into the PKGBUILD. Same with other windows etc

**Comment by telans** [comment]
I've pushed the aur changes and added a desktop entry, if anyone wants to take a look

**Comment by wgpierce** [comment]
@telans that looks good now. Any possibility of changing to samrewritten package name?
After the new icon is added, we can change the icon on the .desktop file to use the new icon.
I think we can wait for Paul to approve this pull now.

**Comment by nomis6432** [comment]
@wgpierce to change the package name you'd have to create a new package with the new name and submit a merge request to merge the old package in the new package.

I only created the AUR package because I needed it myself and thought it could be useful to others. If you want to you can create that new package yourself and I'll submit a merge request on my package in your package.

Note that I've added "samrewritten" to the key words so it will already show up when you search for it.

**Comment by telans** [comment]
Creating a package with the name `samrewritten-git` now

**Comment by telans** [comment]
@nomis6432 https://aur.archlinux.org/packages/samrewritten-git/

**Comment by wgpierce** [comment]
@nomis6432 yeah I figured it would be a little bit of a hassle. Thanks telans. We can wait for Paul to weigh in as well.

**Comment by telans** [comment]
Added you as a co-maintainer too, @wgpierce

**Comment by nomis6432** [comment]
Ok I'll sibmit a merge request. It might take a while since it has to be reviewed by one of the thrusted users.

**Comment by PaulCombal** [comment]
Sorry I didn't really take an in-depth look, but for now if anything works at all it's ok. We're going to release a new version soon, and I would like the release after that to be a "cleanup operation" where all this stuff should be taken care of in-depth. 
Then it would be great to include the PKGBUILD in the git repo.

**Comment by telans** [comment]
Alright, I'll hold off on this and reopen when the new version is released

**Comment by PaulCombal** [comment]
@wgpierce Should merge beta-ipc into master next time he's online, and I'll start doing some cleanup right after, so stay put!

**Comment by wgpierce** [comment]
@telans , reopening for you to rebase on master and I'll accept it.

**Comment by wgpierce** [comment]
oh deleting the branch causes the issue to be closed. @telans if you make a new issue on master, I'll accept it right away!

**Comment by wgpierce** [comment]
Merged in https://github.com/PaulCombal/SamRewritten/pull/17

Thanks @telans! and thanks for adding me as maintainer, though you've got a good handle on it. And thanks @nomis6432 for the original PKGBUILD!

**Pull request closed without merging**
