### PR TITLE
Implement permissions

### PR DESCRIPTION
**Pull request by wgpierce**
Implement the rest of permissions and hook them up to the CLI and eventually GUI.
This brings us to feature parity with the original SAM!

### CODE REVIEW

**Comment by wgpierce** [comment]
@PaulCombal how do you want to show protected stats/achievements in the GUI? SAM showed them as a red background, but because theming, I'm not so sure if that's what we want to do. If you want to implement it yourself now too, feel free.

**Comment by PaulCombal** [comment]
How do you feel about an icon with a lock just like the diamond for "rare" or the chart for "next most achived", and disabling the toggle button on the right?

Also nice work! I really have to think of a way to make the code cleaner imo asap, since I think there will soon be way enough for a release.

**Comment by wgpierce** [comment]
Done:
image

I don't really want to restrict the user from trying to change it in case maybe they find out something can be changed! But there's a big warning sign now.
I put a few cleanups in there too.
I'm ready to merge this now.

**Comment by PaulCombal** [comment]
Alright, feel free to merge when you're ready. Did you have time to look for the achievement permission as well (issue #53) ?

**Comment by wgpierce** [comment]
Yeah achievement permissions are implemented too.

**Pull request merged**
