### PR TITLE
Implement achievement selection operations

### LINKED ISSUE #18: Implement "Select all," "Invert Selection," "Reset," and "Refresh" buttons on achievement windows
This will bring the achievements page to feature parity with the original SAM.
This was requested by a user.

### PR DESCRIPTION
**Pull request by wgpierce**
Plumb full support for unlock all, relock all, and invert
all achievements.

Bring stats/achievements naming into alignment.

Only set achievement lock unlock button as pressed when it's actually
pressed/pending modification and reorient the logic around this.

Reorder signal handlers according to their order in the popup order
Fix some documentation comments

Fixes #18

### CODE REVIEW

**Comment by wgpierce** [comment]
@afonsofrancof please have a look and help me test this. It works well in my testing.

**Comment by afonsofrancof** [comment]
I will test it tonight , thanks alot.

**Comment by PaulCombal** [comment]
I'll review this tonight, but it looks good so far!

**Comment by wgpierce** [comment]
@telans with the last commit, now the user gets feedback on if the current game has no achievements. I think we talked about that before.

Merging this now.

**Pull request merged**
